global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: individuals-api-metrics
    static_configs:
      - targets: ['individuals-api:8081']
    metrics_path: '/actuator/prometheus'