application:
  keycloak:
    port: 8080
    server-uri: http://localhost:${application.keycloak.port}
    issuer-uri: ${application.keycloak.server-uri}/realms/${application.keycloak.realm}
    admin-uri: ${application.keycloak.server-uri}/admin/realms/${application.keycloak.realm}/users
    realm: payment-system
    admin:
      client_id: payment-system-admin-cli