server:
  port: 8081
spring:
  application:
    name: individuals-api
  main:
    web-application-type: reactive
  config:
    import:
      - optional:application-secrets.yaml
      - optional:application-keycloak.yaml
      - optional:application-keycloak-secrets.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.issuer-uri}
          jwk-set-uri: ${application.keycloak.issuer-uri}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: ${application.keycloak.issuer-uri}
            token-uri: ${application.keycloak.server-uri}/realms/${application.keycloak.realm}/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: individuals-api
management:
  metrics:
    tags:
      application: individuals-api
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health